package cn.edu.guet.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlanDesignInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoIsNull() {
            addCriterion("plan_bill_no is null");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoIsNotNull() {
            addCriterion("plan_bill_no is not null");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoEqualTo(String value) {
            addCriterion("plan_bill_no =", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoNotEqualTo(String value) {
            addCriterion("plan_bill_no <>", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoGreaterThan(String value) {
            addCriterion("plan_bill_no >", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoGreaterThanOrEqualTo(String value) {
            addCriterion("plan_bill_no >=", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoLessThan(String value) {
            addCriterion("plan_bill_no <", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoLessThanOrEqualTo(String value) {
            addCriterion("plan_bill_no <=", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoLike(String value) {
            addCriterion("plan_bill_no like", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoNotLike(String value) {
            addCriterion("plan_bill_no not like", value, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoIn(List<String> values) {
            addCriterion("plan_bill_no in", values, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoNotIn(List<String> values) {
            addCriterion("plan_bill_no not in", values, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoBetween(String value1, String value2) {
            addCriterion("plan_bill_no between", value1, value2, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanBillNoNotBetween(String value1, String value2) {
            addCriterion("plan_bill_no not between", value1, value2, "planBillNo");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameIsNull() {
            addCriterion("plan_design_name is null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameIsNotNull() {
            addCriterion("plan_design_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameEqualTo(String value) {
            addCriterion("plan_design_name =", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameNotEqualTo(String value) {
            addCriterion("plan_design_name <>", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameGreaterThan(String value) {
            addCriterion("plan_design_name >", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameGreaterThanOrEqualTo(String value) {
            addCriterion("plan_design_name >=", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameLessThan(String value) {
            addCriterion("plan_design_name <", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameLessThanOrEqualTo(String value) {
            addCriterion("plan_design_name <=", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameLike(String value) {
            addCriterion("plan_design_name like", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameNotLike(String value) {
            addCriterion("plan_design_name not like", value, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameIn(List<String> values) {
            addCriterion("plan_design_name in", values, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameNotIn(List<String> values) {
            addCriterion("plan_design_name not in", values, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameBetween(String value1, String value2) {
            addCriterion("plan_design_name between", value1, value2, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andPlanDesignNameNotBetween(String value1, String value2) {
            addCriterion("plan_design_name not between", value1, value2, "planDesignName");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyIsNull() {
            addCriterion("design_company is null");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyIsNotNull() {
            addCriterion("design_company is not null");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyEqualTo(String value) {
            addCriterion("design_company =", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyNotEqualTo(String value) {
            addCriterion("design_company <>", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyGreaterThan(String value) {
            addCriterion("design_company >", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("design_company >=", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyLessThan(String value) {
            addCriterion("design_company <", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyLessThanOrEqualTo(String value) {
            addCriterion("design_company <=", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyLike(String value) {
            addCriterion("design_company like", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyNotLike(String value) {
            addCriterion("design_company not like", value, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyIn(List<String> values) {
            addCriterion("design_company in", values, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyNotIn(List<String> values) {
            addCriterion("design_company not in", values, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyBetween(String value1, String value2) {
            addCriterion("design_company between", value1, value2, "designCompany");
            return (Criteria) this;
        }

        public Criteria andDesignCompanyNotBetween(String value1, String value2) {
            addCriterion("design_company not between", value1, value2, "designCompany");
            return (Criteria) this;
        }

        public Criteria andSpecIdIsNull() {
            addCriterion("spec_id is null");
            return (Criteria) this;
        }

        public Criteria andSpecIdIsNotNull() {
            addCriterion("spec_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpecIdEqualTo(Short value) {
            addCriterion("spec_id =", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotEqualTo(Short value) {
            addCriterion("spec_id <>", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdGreaterThan(Short value) {
            addCriterion("spec_id >", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdGreaterThanOrEqualTo(Short value) {
            addCriterion("spec_id >=", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdLessThan(Short value) {
            addCriterion("spec_id <", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdLessThanOrEqualTo(Short value) {
            addCriterion("spec_id <=", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdIn(List<Short> values) {
            addCriterion("spec_id in", values, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotIn(List<Short> values) {
            addCriterion("spec_id not in", values, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdBetween(Short value1, Short value2) {
            addCriterion("spec_id between", value1, value2, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotBetween(Short value1, Short value2) {
            addCriterion("spec_id not between", value1, value2, "specId");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorIsNull() {
            addCriterion("project_director is null");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorIsNotNull() {
            addCriterion("project_director is not null");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorEqualTo(String value) {
            addCriterion("project_director =", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorNotEqualTo(String value) {
            addCriterion("project_director <>", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorGreaterThan(String value) {
            addCriterion("project_director >", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorGreaterThanOrEqualTo(String value) {
            addCriterion("project_director >=", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorLessThan(String value) {
            addCriterion("project_director <", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorLessThanOrEqualTo(String value) {
            addCriterion("project_director <=", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorLike(String value) {
            addCriterion("project_director like", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorNotLike(String value) {
            addCriterion("project_director not like", value, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorIn(List<String> values) {
            addCriterion("project_director in", values, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorNotIn(List<String> values) {
            addCriterion("project_director not in", values, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorBetween(String value1, String value2) {
            addCriterion("project_director between", value1, value2, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andProjectDirectorNotBetween(String value1, String value2) {
            addCriterion("project_director not between", value1, value2, "projectDirector");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderIsNull() {
            addCriterion("spec_leader is null");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderIsNotNull() {
            addCriterion("spec_leader is not null");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderEqualTo(String value) {
            addCriterion("spec_leader =", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderNotEqualTo(String value) {
            addCriterion("spec_leader <>", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderGreaterThan(String value) {
            addCriterion("spec_leader >", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("spec_leader >=", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderLessThan(String value) {
            addCriterion("spec_leader <", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderLessThanOrEqualTo(String value) {
            addCriterion("spec_leader <=", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderLike(String value) {
            addCriterion("spec_leader like", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderNotLike(String value) {
            addCriterion("spec_leader not like", value, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderIn(List<String> values) {
            addCriterion("spec_leader in", values, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderNotIn(List<String> values) {
            addCriterion("spec_leader not in", values, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderBetween(String value1, String value2) {
            addCriterion("spec_leader between", value1, value2, "specLeader");
            return (Criteria) this;
        }

        public Criteria andSpecLeaderNotBetween(String value1, String value2) {
            addCriterion("spec_leader not between", value1, value2, "specLeader");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNull() {
            addCriterion("designer is null");
            return (Criteria) this;
        }

        public Criteria andDesignerIsNotNull() {
            addCriterion("designer is not null");
            return (Criteria) this;
        }

        public Criteria andDesignerEqualTo(String value) {
            addCriterion("designer =", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotEqualTo(String value) {
            addCriterion("designer <>", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThan(String value) {
            addCriterion("designer >", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerGreaterThanOrEqualTo(String value) {
            addCriterion("designer >=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThan(String value) {
            addCriterion("designer <", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLessThanOrEqualTo(String value) {
            addCriterion("designer <=", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerLike(String value) {
            addCriterion("designer like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotLike(String value) {
            addCriterion("designer not like", value, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerIn(List<String> values) {
            addCriterion("designer in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotIn(List<String> values) {
            addCriterion("designer not in", values, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerBetween(String value1, String value2) {
            addCriterion("designer between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andDesignerNotBetween(String value1, String value2) {
            addCriterion("designer not between", value1, value2, "designer");
            return (Criteria) this;
        }

        public Criteria andReviewerIsNull() {
            addCriterion("reviewer is null");
            return (Criteria) this;
        }

        public Criteria andReviewerIsNotNull() {
            addCriterion("reviewer is not null");
            return (Criteria) this;
        }

        public Criteria andReviewerEqualTo(String value) {
            addCriterion("reviewer =", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotEqualTo(String value) {
            addCriterion("reviewer <>", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerGreaterThan(String value) {
            addCriterion("reviewer >", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerGreaterThanOrEqualTo(String value) {
            addCriterion("reviewer >=", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLessThan(String value) {
            addCriterion("reviewer <", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLessThanOrEqualTo(String value) {
            addCriterion("reviewer <=", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerLike(String value) {
            addCriterion("reviewer like", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotLike(String value) {
            addCriterion("reviewer not like", value, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerIn(List<String> values) {
            addCriterion("reviewer in", values, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotIn(List<String> values) {
            addCriterion("reviewer not in", values, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerBetween(String value1, String value2) {
            addCriterion("reviewer between", value1, value2, "reviewer");
            return (Criteria) this;
        }

        public Criteria andReviewerNotBetween(String value1, String value2) {
            addCriterion("reviewer not between", value1, value2, "reviewer");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Byte value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Byte value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Byte value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Byte value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Byte value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Byte value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Byte> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Byte> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Byte value1, Byte value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Byte value1, Byte value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIsNull() {
            addCriterion("system_cad_file_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIsNotNull() {
            addCriterion("system_cad_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdEqualTo(Integer value) {
            addCriterion("system_cad_file_id =", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotEqualTo(Integer value) {
            addCriterion("system_cad_file_id <>", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdGreaterThan(Integer value) {
            addCriterion("system_cad_file_id >", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_cad_file_id >=", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdLessThan(Integer value) {
            addCriterion("system_cad_file_id <", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_cad_file_id <=", value, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdIn(List<Integer> values) {
            addCriterion("system_cad_file_id in", values, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotIn(List<Integer> values) {
            addCriterion("system_cad_file_id not in", values, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdBetween(Integer value1, Integer value2) {
            addCriterion("system_cad_file_id between", value1, value2, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_cad_file_id not between", value1, value2, "systemCadFileId");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIsNull() {
            addCriterion("system_cad_file_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIsNotNull() {
            addCriterion("system_cad_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameEqualTo(String value) {
            addCriterion("system_cad_file_name =", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotEqualTo(String value) {
            addCriterion("system_cad_file_name <>", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameGreaterThan(String value) {
            addCriterion("system_cad_file_name >", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_cad_file_name >=", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLessThan(String value) {
            addCriterion("system_cad_file_name <", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLessThanOrEqualTo(String value) {
            addCriterion("system_cad_file_name <=", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameLike(String value) {
            addCriterion("system_cad_file_name like", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotLike(String value) {
            addCriterion("system_cad_file_name not like", value, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameIn(List<String> values) {
            addCriterion("system_cad_file_name in", values, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotIn(List<String> values) {
            addCriterion("system_cad_file_name not in", values, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameBetween(String value1, String value2) {
            addCriterion("system_cad_file_name between", value1, value2, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileNameNotBetween(String value1, String value2) {
            addCriterion("system_cad_file_name not between", value1, value2, "systemCadFileName");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIsNull() {
            addCriterion("system_cad_file_url is null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIsNotNull() {
            addCriterion("system_cad_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlEqualTo(String value) {
            addCriterion("system_cad_file_url =", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotEqualTo(String value) {
            addCriterion("system_cad_file_url <>", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlGreaterThan(String value) {
            addCriterion("system_cad_file_url >", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("system_cad_file_url >=", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLessThan(String value) {
            addCriterion("system_cad_file_url <", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLessThanOrEqualTo(String value) {
            addCriterion("system_cad_file_url <=", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlLike(String value) {
            addCriterion("system_cad_file_url like", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotLike(String value) {
            addCriterion("system_cad_file_url not like", value, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlIn(List<String> values) {
            addCriterion("system_cad_file_url in", values, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotIn(List<String> values) {
            addCriterion("system_cad_file_url not in", values, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlBetween(String value1, String value2) {
            addCriterion("system_cad_file_url between", value1, value2, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemCadFileUrlNotBetween(String value1, String value2) {
            addCriterion("system_cad_file_url not between", value1, value2, "systemCadFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIsNull() {
            addCriterion("system_excel_file_id is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIsNotNull() {
            addCriterion("system_excel_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdEqualTo(Integer value) {
            addCriterion("system_excel_file_id =", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotEqualTo(Integer value) {
            addCriterion("system_excel_file_id <>", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdGreaterThan(Integer value) {
            addCriterion("system_excel_file_id >", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_excel_file_id >=", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdLessThan(Integer value) {
            addCriterion("system_excel_file_id <", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("system_excel_file_id <=", value, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdIn(List<Integer> values) {
            addCriterion("system_excel_file_id in", values, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotIn(List<Integer> values) {
            addCriterion("system_excel_file_id not in", values, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdBetween(Integer value1, Integer value2) {
            addCriterion("system_excel_file_id between", value1, value2, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("system_excel_file_id not between", value1, value2, "systemExcelFileId");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIsNull() {
            addCriterion("system_excel_file_name is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIsNotNull() {
            addCriterion("system_excel_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameEqualTo(String value) {
            addCriterion("system_excel_file_name =", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotEqualTo(String value) {
            addCriterion("system_excel_file_name <>", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameGreaterThan(String value) {
            addCriterion("system_excel_file_name >", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("system_excel_file_name >=", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLessThan(String value) {
            addCriterion("system_excel_file_name <", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLessThanOrEqualTo(String value) {
            addCriterion("system_excel_file_name <=", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameLike(String value) {
            addCriterion("system_excel_file_name like", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotLike(String value) {
            addCriterion("system_excel_file_name not like", value, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameIn(List<String> values) {
            addCriterion("system_excel_file_name in", values, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotIn(List<String> values) {
            addCriterion("system_excel_file_name not in", values, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameBetween(String value1, String value2) {
            addCriterion("system_excel_file_name between", value1, value2, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileNameNotBetween(String value1, String value2) {
            addCriterion("system_excel_file_name not between", value1, value2, "systemExcelFileName");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIsNull() {
            addCriterion("system_excel_file_url is null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIsNotNull() {
            addCriterion("system_excel_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlEqualTo(String value) {
            addCriterion("system_excel_file_url =", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotEqualTo(String value) {
            addCriterion("system_excel_file_url <>", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlGreaterThan(String value) {
            addCriterion("system_excel_file_url >", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("system_excel_file_url >=", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLessThan(String value) {
            addCriterion("system_excel_file_url <", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLessThanOrEqualTo(String value) {
            addCriterion("system_excel_file_url <=", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlLike(String value) {
            addCriterion("system_excel_file_url like", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotLike(String value) {
            addCriterion("system_excel_file_url not like", value, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlIn(List<String> values) {
            addCriterion("system_excel_file_url in", values, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotIn(List<String> values) {
            addCriterion("system_excel_file_url not in", values, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlBetween(String value1, String value2) {
            addCriterion("system_excel_file_url between", value1, value2, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andSystemExcelFileUrlNotBetween(String value1, String value2) {
            addCriterion("system_excel_file_url not between", value1, value2, "systemExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIsNull() {
            addCriterion("channel_excel_file_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIsNotNull() {
            addCriterion("channel_excel_file_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdEqualTo(Integer value) {
            addCriterion("channel_excel_file_id =", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotEqualTo(Integer value) {
            addCriterion("channel_excel_file_id <>", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdGreaterThan(Integer value) {
            addCriterion("channel_excel_file_id >", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_excel_file_id >=", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdLessThan(Integer value) {
            addCriterion("channel_excel_file_id <", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdLessThanOrEqualTo(Integer value) {
            addCriterion("channel_excel_file_id <=", value, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdIn(List<Integer> values) {
            addCriterion("channel_excel_file_id in", values, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotIn(List<Integer> values) {
            addCriterion("channel_excel_file_id not in", values, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdBetween(Integer value1, Integer value2) {
            addCriterion("channel_excel_file_id between", value1, value2, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileIdNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_excel_file_id not between", value1, value2, "channelExcelFileId");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIsNull() {
            addCriterion("channel_excel_file_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIsNotNull() {
            addCriterion("channel_excel_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameEqualTo(String value) {
            addCriterion("channel_excel_file_name =", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotEqualTo(String value) {
            addCriterion("channel_excel_file_name <>", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameGreaterThan(String value) {
            addCriterion("channel_excel_file_name >", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_name >=", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLessThan(String value) {
            addCriterion("channel_excel_file_name <", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLessThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_name <=", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameLike(String value) {
            addCriterion("channel_excel_file_name like", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotLike(String value) {
            addCriterion("channel_excel_file_name not like", value, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameIn(List<String> values) {
            addCriterion("channel_excel_file_name in", values, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotIn(List<String> values) {
            addCriterion("channel_excel_file_name not in", values, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameBetween(String value1, String value2) {
            addCriterion("channel_excel_file_name between", value1, value2, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileNameNotBetween(String value1, String value2) {
            addCriterion("channel_excel_file_name not between", value1, value2, "channelExcelFileName");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIsNull() {
            addCriterion("channel_excel_file_url is null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIsNotNull() {
            addCriterion("channel_excel_file_url is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlEqualTo(String value) {
            addCriterion("channel_excel_file_url =", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotEqualTo(String value) {
            addCriterion("channel_excel_file_url <>", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlGreaterThan(String value) {
            addCriterion("channel_excel_file_url >", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlGreaterThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_url >=", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLessThan(String value) {
            addCriterion("channel_excel_file_url <", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLessThanOrEqualTo(String value) {
            addCriterion("channel_excel_file_url <=", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlLike(String value) {
            addCriterion("channel_excel_file_url like", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotLike(String value) {
            addCriterion("channel_excel_file_url not like", value, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlIn(List<String> values) {
            addCriterion("channel_excel_file_url in", values, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotIn(List<String> values) {
            addCriterion("channel_excel_file_url not in", values, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlBetween(String value1, String value2) {
            addCriterion("channel_excel_file_url between", value1, value2, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andChannelExcelFileUrlNotBetween(String value1, String value2) {
            addCriterion("channel_excel_file_url not between", value1, value2, "channelExcelFileUrl");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftIsNull() {
            addCriterion("cad_coord_left is null");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftIsNotNull() {
            addCriterion("cad_coord_left is not null");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftEqualTo(Integer value) {
            addCriterion("cad_coord_left =", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftNotEqualTo(Integer value) {
            addCriterion("cad_coord_left <>", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftGreaterThan(Integer value) {
            addCriterion("cad_coord_left >", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftGreaterThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_left >=", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftLessThan(Integer value) {
            addCriterion("cad_coord_left <", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftLessThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_left <=", value, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftIn(List<Integer> values) {
            addCriterion("cad_coord_left in", values, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftNotIn(List<Integer> values) {
            addCriterion("cad_coord_left not in", values, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_left between", value1, value2, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordLeftNotBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_left not between", value1, value2, "cadCoordLeft");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopIsNull() {
            addCriterion("cad_coord_top is null");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopIsNotNull() {
            addCriterion("cad_coord_top is not null");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopEqualTo(Integer value) {
            addCriterion("cad_coord_top =", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopNotEqualTo(Integer value) {
            addCriterion("cad_coord_top <>", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopGreaterThan(Integer value) {
            addCriterion("cad_coord_top >", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_top >=", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopLessThan(Integer value) {
            addCriterion("cad_coord_top <", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopLessThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_top <=", value, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopIn(List<Integer> values) {
            addCriterion("cad_coord_top in", values, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopNotIn(List<Integer> values) {
            addCriterion("cad_coord_top not in", values, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_top between", value1, value2, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordTopNotBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_top not between", value1, value2, "cadCoordTop");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightIsNull() {
            addCriterion("cad_coord_right is null");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightIsNotNull() {
            addCriterion("cad_coord_right is not null");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightEqualTo(Integer value) {
            addCriterion("cad_coord_right =", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightNotEqualTo(Integer value) {
            addCriterion("cad_coord_right <>", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightGreaterThan(Integer value) {
            addCriterion("cad_coord_right >", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_right >=", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightLessThan(Integer value) {
            addCriterion("cad_coord_right <", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightLessThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_right <=", value, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightIn(List<Integer> values) {
            addCriterion("cad_coord_right in", values, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightNotIn(List<Integer> values) {
            addCriterion("cad_coord_right not in", values, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_right between", value1, value2, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordRightNotBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_right not between", value1, value2, "cadCoordRight");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomIsNull() {
            addCriterion("cad_coord_bottom is null");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomIsNotNull() {
            addCriterion("cad_coord_bottom is not null");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomEqualTo(Integer value) {
            addCriterion("cad_coord_bottom =", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomNotEqualTo(Integer value) {
            addCriterion("cad_coord_bottom <>", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomGreaterThan(Integer value) {
            addCriterion("cad_coord_bottom >", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomGreaterThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_bottom >=", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomLessThan(Integer value) {
            addCriterion("cad_coord_bottom <", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomLessThanOrEqualTo(Integer value) {
            addCriterion("cad_coord_bottom <=", value, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomIn(List<Integer> values) {
            addCriterion("cad_coord_bottom in", values, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomNotIn(List<Integer> values) {
            addCriterion("cad_coord_bottom not in", values, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_bottom between", value1, value2, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andCadCoordBottomNotBetween(Integer value1, Integer value2) {
            addCriterion("cad_coord_bottom not between", value1, value2, "cadCoordBottom");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Integer value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Integer value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Integer value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Integer value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Integer> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Integer> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 21 17:13:06 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}