package cn.edu.guet.bean;

import java.io.Serializable;
import java.util.Date;

public class PlanDesignInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.Id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.plan_bill_no
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String planBillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.plan_design_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String planDesignName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.design_company
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String designCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.spec_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Short specId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.project_director
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String projectDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.spec_leader
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String specLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.designer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String designer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.reviewer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.source
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer systemCadFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String systemCadFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String systemCadFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer systemExcelFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String systemExcelFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String systemExcelFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer channelExcelFileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String channelExcelFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String channelExcelFileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.cad_coord_left
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer cadCoordLeft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.cad_coord_top
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer cadCoordTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.cad_coord_right
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer cadCoordRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.cad_coord_bottom
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer cadCoordBottom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.staff_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.staff_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.create_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plan_design_info.update_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.Id
     *
     * @return the value of t_plan_design_info.Id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.Id
     *
     * @param id the value for t_plan_design_info.Id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.plan_bill_no
     *
     * @return the value of t_plan_design_info.plan_bill_no
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getPlanBillNo() {
        return planBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withPlanBillNo(String planBillNo) {
        this.setPlanBillNo(planBillNo);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.plan_bill_no
     *
     * @param planBillNo the value for t_plan_design_info.plan_bill_no
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setPlanBillNo(String planBillNo) {
        this.planBillNo = planBillNo == null ? null : planBillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.plan_design_name
     *
     * @return the value of t_plan_design_info.plan_design_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getPlanDesignName() {
        return planDesignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withPlanDesignName(String planDesignName) {
        this.setPlanDesignName(planDesignName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.plan_design_name
     *
     * @param planDesignName the value for t_plan_design_info.plan_design_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setPlanDesignName(String planDesignName) {
        this.planDesignName = planDesignName == null ? null : planDesignName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.design_company
     *
     * @return the value of t_plan_design_info.design_company
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getDesignCompany() {
        return designCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withDesignCompany(String designCompany) {
        this.setDesignCompany(designCompany);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.design_company
     *
     * @param designCompany the value for t_plan_design_info.design_company
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setDesignCompany(String designCompany) {
        this.designCompany = designCompany == null ? null : designCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.spec_id
     *
     * @return the value of t_plan_design_info.spec_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Short getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSpecId(Short specId) {
        this.setSpecId(specId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.spec_id
     *
     * @param specId the value for t_plan_design_info.spec_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSpecId(Short specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.project_director
     *
     * @return the value of t_plan_design_info.project_director
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getProjectDirector() {
        return projectDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withProjectDirector(String projectDirector) {
        this.setProjectDirector(projectDirector);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.project_director
     *
     * @param projectDirector the value for t_plan_design_info.project_director
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setProjectDirector(String projectDirector) {
        this.projectDirector = projectDirector == null ? null : projectDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.spec_leader
     *
     * @return the value of t_plan_design_info.spec_leader
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getSpecLeader() {
        return specLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSpecLeader(String specLeader) {
        this.setSpecLeader(specLeader);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.spec_leader
     *
     * @param specLeader the value for t_plan_design_info.spec_leader
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSpecLeader(String specLeader) {
        this.specLeader = specLeader == null ? null : specLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.designer
     *
     * @return the value of t_plan_design_info.designer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getDesigner() {
        return designer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withDesigner(String designer) {
        this.setDesigner(designer);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.designer
     *
     * @param designer the value for t_plan_design_info.designer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setDesigner(String designer) {
        this.designer = designer == null ? null : designer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.reviewer
     *
     * @return the value of t_plan_design_info.reviewer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withReviewer(String reviewer) {
        this.setReviewer(reviewer);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.reviewer
     *
     * @param reviewer the value for t_plan_design_info.reviewer
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.source
     *
     * @return the value of t_plan_design_info.source
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSource(Byte source) {
        this.setSource(source);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.source
     *
     * @param source the value for t_plan_design_info.source
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_cad_file_id
     *
     * @return the value of t_plan_design_info.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getSystemCadFileId() {
        return systemCadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemCadFileId(Integer systemCadFileId) {
        this.setSystemCadFileId(systemCadFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_cad_file_id
     *
     * @param systemCadFileId the value for t_plan_design_info.system_cad_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemCadFileId(Integer systemCadFileId) {
        this.systemCadFileId = systemCadFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_cad_file_name
     *
     * @return the value of t_plan_design_info.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getSystemCadFileName() {
        return systemCadFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemCadFileName(String systemCadFileName) {
        this.setSystemCadFileName(systemCadFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_cad_file_name
     *
     * @param systemCadFileName the value for t_plan_design_info.system_cad_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemCadFileName(String systemCadFileName) {
        this.systemCadFileName = systemCadFileName == null ? null : systemCadFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_cad_file_url
     *
     * @return the value of t_plan_design_info.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getSystemCadFileUrl() {
        return systemCadFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemCadFileUrl(String systemCadFileUrl) {
        this.setSystemCadFileUrl(systemCadFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_cad_file_url
     *
     * @param systemCadFileUrl the value for t_plan_design_info.system_cad_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemCadFileUrl(String systemCadFileUrl) {
        this.systemCadFileUrl = systemCadFileUrl == null ? null : systemCadFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_excel_file_id
     *
     * @return the value of t_plan_design_info.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getSystemExcelFileId() {
        return systemExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemExcelFileId(Integer systemExcelFileId) {
        this.setSystemExcelFileId(systemExcelFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_excel_file_id
     *
     * @param systemExcelFileId the value for t_plan_design_info.system_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemExcelFileId(Integer systemExcelFileId) {
        this.systemExcelFileId = systemExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_excel_file_name
     *
     * @return the value of t_plan_design_info.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getSystemExcelFileName() {
        return systemExcelFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemExcelFileName(String systemExcelFileName) {
        this.setSystemExcelFileName(systemExcelFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_excel_file_name
     *
     * @param systemExcelFileName the value for t_plan_design_info.system_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemExcelFileName(String systemExcelFileName) {
        this.systemExcelFileName = systemExcelFileName == null ? null : systemExcelFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.system_excel_file_url
     *
     * @return the value of t_plan_design_info.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getSystemExcelFileUrl() {
        return systemExcelFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withSystemExcelFileUrl(String systemExcelFileUrl) {
        this.setSystemExcelFileUrl(systemExcelFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.system_excel_file_url
     *
     * @param systemExcelFileUrl the value for t_plan_design_info.system_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setSystemExcelFileUrl(String systemExcelFileUrl) {
        this.systemExcelFileUrl = systemExcelFileUrl == null ? null : systemExcelFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.channel_excel_file_id
     *
     * @return the value of t_plan_design_info.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getChannelExcelFileId() {
        return channelExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withChannelExcelFileId(Integer channelExcelFileId) {
        this.setChannelExcelFileId(channelExcelFileId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.channel_excel_file_id
     *
     * @param channelExcelFileId the value for t_plan_design_info.channel_excel_file_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setChannelExcelFileId(Integer channelExcelFileId) {
        this.channelExcelFileId = channelExcelFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.channel_excel_file_name
     *
     * @return the value of t_plan_design_info.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getChannelExcelFileName() {
        return channelExcelFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withChannelExcelFileName(String channelExcelFileName) {
        this.setChannelExcelFileName(channelExcelFileName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.channel_excel_file_name
     *
     * @param channelExcelFileName the value for t_plan_design_info.channel_excel_file_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setChannelExcelFileName(String channelExcelFileName) {
        this.channelExcelFileName = channelExcelFileName == null ? null : channelExcelFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.channel_excel_file_url
     *
     * @return the value of t_plan_design_info.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getChannelExcelFileUrl() {
        return channelExcelFileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withChannelExcelFileUrl(String channelExcelFileUrl) {
        this.setChannelExcelFileUrl(channelExcelFileUrl);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.channel_excel_file_url
     *
     * @param channelExcelFileUrl the value for t_plan_design_info.channel_excel_file_url
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setChannelExcelFileUrl(String channelExcelFileUrl) {
        this.channelExcelFileUrl = channelExcelFileUrl == null ? null : channelExcelFileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.cad_coord_left
     *
     * @return the value of t_plan_design_info.cad_coord_left
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getCadCoordLeft() {
        return cadCoordLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withCadCoordLeft(Integer cadCoordLeft) {
        this.setCadCoordLeft(cadCoordLeft);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.cad_coord_left
     *
     * @param cadCoordLeft the value for t_plan_design_info.cad_coord_left
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setCadCoordLeft(Integer cadCoordLeft) {
        this.cadCoordLeft = cadCoordLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.cad_coord_top
     *
     * @return the value of t_plan_design_info.cad_coord_top
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getCadCoordTop() {
        return cadCoordTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withCadCoordTop(Integer cadCoordTop) {
        this.setCadCoordTop(cadCoordTop);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.cad_coord_top
     *
     * @param cadCoordTop the value for t_plan_design_info.cad_coord_top
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setCadCoordTop(Integer cadCoordTop) {
        this.cadCoordTop = cadCoordTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.cad_coord_right
     *
     * @return the value of t_plan_design_info.cad_coord_right
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getCadCoordRight() {
        return cadCoordRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withCadCoordRight(Integer cadCoordRight) {
        this.setCadCoordRight(cadCoordRight);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.cad_coord_right
     *
     * @param cadCoordRight the value for t_plan_design_info.cad_coord_right
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setCadCoordRight(Integer cadCoordRight) {
        this.cadCoordRight = cadCoordRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.cad_coord_bottom
     *
     * @return the value of t_plan_design_info.cad_coord_bottom
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getCadCoordBottom() {
        return cadCoordBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withCadCoordBottom(Integer cadCoordBottom) {
        this.setCadCoordBottom(cadCoordBottom);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.cad_coord_bottom
     *
     * @param cadCoordBottom the value for t_plan_design_info.cad_coord_bottom
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setCadCoordBottom(Integer cadCoordBottom) {
        this.cadCoordBottom = cadCoordBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.staff_id
     *
     * @return the value of t_plan_design_info.staff_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withStaffId(Integer staffId) {
        this.setStaffId(staffId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.staff_id
     *
     * @param staffId the value for t_plan_design_info.staff_id
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.staff_name
     *
     * @return the value of t_plan_design_info.staff_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withStaffName(String staffName) {
        this.setStaffName(staffName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.staff_name
     *
     * @param staffName the value for t_plan_design_info.staff_name
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.create_time
     *
     * @return the value of t_plan_design_info.create_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.create_time
     *
     * @param createTime the value for t_plan_design_info.create_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plan_design_info.update_time
     *
     * @return the value of t_plan_design_info.update_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public PlanDesignInfo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plan_design_info.update_time
     *
     * @param updateTime the value for t_plan_design_info.update_time
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", planBillNo=").append(planBillNo);
        sb.append(", planDesignName=").append(planDesignName);
        sb.append(", designCompany=").append(designCompany);
        sb.append(", specId=").append(specId);
        sb.append(", projectDirector=").append(projectDirector);
        sb.append(", specLeader=").append(specLeader);
        sb.append(", designer=").append(designer);
        sb.append(", reviewer=").append(reviewer);
        sb.append(", source=").append(source);
        sb.append(", systemCadFileId=").append(systemCadFileId);
        sb.append(", systemCadFileName=").append(systemCadFileName);
        sb.append(", systemCadFileUrl=").append(systemCadFileUrl);
        sb.append(", systemExcelFileId=").append(systemExcelFileId);
        sb.append(", systemExcelFileName=").append(systemExcelFileName);
        sb.append(", systemExcelFileUrl=").append(systemExcelFileUrl);
        sb.append(", channelExcelFileId=").append(channelExcelFileId);
        sb.append(", channelExcelFileName=").append(channelExcelFileName);
        sb.append(", channelExcelFileUrl=").append(channelExcelFileUrl);
        sb.append(", cadCoordLeft=").append(cadCoordLeft);
        sb.append(", cadCoordTop=").append(cadCoordTop);
        sb.append(", cadCoordRight=").append(cadCoordRight);
        sb.append(", cadCoordBottom=").append(cadCoordBottom);
        sb.append(", staffId=").append(staffId);
        sb.append(", staffName=").append(staffName);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}