package cn.edu.guet.mapper;

import cn.edu.guet.bean.PlanDesignDTO;
import cn.edu.guet.bean.PlanDesignInfo;
import cn.edu.guet.bean.PlanDesignInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlanDesignInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    long countByExample(PlanDesignInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int deleteByExample(PlanDesignInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int insert(PlanDesignInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int insertSelective(PlanDesignInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    List<PlanDesignInfo> selectByExampleWithRowbounds(PlanDesignInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    List<PlanDesignInfo> selectByExample(PlanDesignInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    PlanDesignInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int updateByExampleSelective(@Param("record") PlanDesignInfo record, @Param("example") PlanDesignInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int updateByExample(@Param("record") PlanDesignInfo record, @Param("example") PlanDesignInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int updateByPrimaryKeySelective(PlanDesignInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plan_design_info
     *
     * @mbg.generated Wed Jun 21 17:13:06 CST 2023
     */
    int updateByPrimaryKey(PlanDesignInfo record);

    /**
     * 获取工单号
     */
    String selectPlanBillNo();

    List<PlanDesignInfo> searchBill(PlanDesignDTO planDesignDTO);

    int countSearchBill(PlanDesignDTO planDesignDTO);

}